language: c
compiler:
  - gcc
# Change this to your needs
install:
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install gperf
  - sudo apt-get install check
  - sudo apt-get install help2man
  - sudo apt-get install python-pip
  - sudo pip install behave flake8
before_script:
  - ./autogen.sh
  - make
script:
  - make check
  - make distcheck
  - flake8
  - behave
notifications:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
    skip_join: true
